name: ci 
on: [push]
jobs: 
  unit-test: 
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: [ '12', '14', '16']
    steps:
      - name: Recuperation du repository
        uses: actions/checkout@v3
      - name: installation de node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: install des dépendances 
        run: npm i 
      - name: test unitaire
        run: npm run test
      - name: code coverage
        run: npm run cover

          
